# Generated by Django 5.2.7 on 2025-10-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], max_length=45)),
                ('descricao', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(default='ATIVO', max_length=45)),
            ],
            options={
                'db_table': 'Classificacao',
            },
        ),
        migrations.CreateModel(
            name='MovimentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGAR', 'A Pagar'), ('RECEBER', 'A Receber')], max_length=45)),
                ('numeronotafiscal', models.CharField(max_length=45)),
                ('dataemissao', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('valortotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDENTE', max_length=45)),
            ],
            options={
                'db_table': 'MovimentoContas',
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('FATURADO', 'Faturado')], max_length=45)),
                ('razaosocial', models.CharField(max_length=150)),
                ('fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(max_length=45, unique=True)),
                ('status', models.CharField(default='ATIVO', max_length=45)),
            ],
            options={
                'db_table': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='MovimentoContasHasClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.ForeignKey(db_column='Classificacao_idClassificacao', on_delete=django.db.models.deletion.CASCADE, to='extrator.classificacao')),
                ('movimentocontas', models.ForeignKey(db_column='MovimentoContas_idMovimentoContas', on_delete=django.db.models.deletion.CASCADE, to='extrator.movimentocontas')),
            ],
            options={
                'db_table': 'MovimentoContas_has_Classificacao',
                'unique_together': {('movimentocontas', 'classificacao')},
            },
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='classificacoes',
            field=models.ManyToManyField(through='extrator.MovimentoContasHasClassificacao', to='extrator.classificacao'),
        ),
        migrations.CreateModel(
            name='ParcelasContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=45)),
                ('datavencimento', models.DateField()),
                ('valorparcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorpago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valorsaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statusparcela', models.CharField(default='PENDENTE', max_length=45)),
                ('movimento', models.ForeignKey(db_column='MovimentoContas_idMovimentoContas', on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='extrator.movimentocontas')),
            ],
            options={
                'db_table': 'ParcelasContas',
            },
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='faturado',
            field=models.ForeignKey(db_column='Pessoas_idFaturado', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_faturado', to='extrator.pessoas'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='fornecedor',
            field=models.ForeignKey(db_column='Pessoas_idFornecedorCliente', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_fornecedor', to='extrator.pessoas'),
        ),
    ]
